title: MapLesotho
safe:           false
source:         app
exclude:
  - assets/vendor
  - assets/styles
  - README.md
timezone: Europe/Dublin
highlighter: false

baseurl: ""
siteurl: "http://www.maplesotho.com"
highlighter: rouge

media_folder: "app/assets/graphics/uploads"
public_folder: "/assets/graphics/uploads"

permalink: pretty
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      psection: "Blog"
      phome: "/"
      permalink: /blog/:year/:month/:day/:title/
gems:
  - jekyll-last-modified-at